version: "${VERSION}"

networks:
  net_dock:

volumes:
  v_wordpress:
  v_mariadb:

services:

  mariadb:
    container_name: mariadb
    build: images/mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABSE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      - net_dock
    volumes:
      - v_mariadb:/v_db
    restart: unless-stopped
    init: true
    stdin_open: true
    tty: true

  nginx:
    depends_on:
    - wordpress_php
    container_name: nginx
    build: images/nginx
    networks:
      - net_dock
    ports:
      - "1024:80"
    volumes:
      - v_wordpress:/v_w
    restart: always
    stdin_open: true
    tty: true

  wordpress_php:
    depends_on:
    - mariadb
    container_name: wordpress-php
    build: images/wordpress-php
    environment:
      MARIADB_DATABSE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      - net_dock
    volumes:
      - v_wordpress:/v_w
    restart: unless-stopped
    #restart: always
    stdin_open: true
    tty: true


