version: '3'

networks:
  net_dock:
    driver: bridge

volumes:
  v_wordpress:
  v_mariadb:

services:

  nginx:
    container_name: nginx
    build: images/nginx
    networks:
      - net_dock
    ports:
      - "1024:80"
    volumes:
      - v_wordpress:/v_w
    stdin_open: true
    tty: true

  wordpress_php:
    container_name: wordpress-php
    build: images/wordpress-php
    networks:
      - net_dock
    ports:
      - "1025:81"
    volumes:
      - v_wordpress:/v_w
    stdin_open: true
    tty: true

  mariadb:
    container_name: mariaDB
    build: images/mariadb
    networks:
      - net_dock
    volumes:
      - v_mariadb:/v_db
    stdin_open: true
    tty: true
